//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUpdator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppUpdator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[XX_EXTENDED_WARRANTY]    Script Date: 12/14/2015 16:32:15 ******/
        ///BEGIN
        ///	IF NOT EXISTS (
        ///			SELECT *
        ///			FROM sys.objects
        ///			WHERE object_id = OBJECT_ID(N&apos;[dbo].[XX_EXTENDED_WARRANTY]&apos;)
        ///				AND type IN (N&apos;U&apos;)
        ///			)
        ///	BEGIN
        ///		CREATE TABLE [dbo].[XX_EXTENDED_WARRANTY] (
        ///			[warranty_id] [int] IDENTITY(1, 1) NOT NULL
        ///			,[warranty_number] [varchar](25) NULL
        ///			,[show_room] [varchar](3) NULL
        ///			,[cash_memo] [varchar](15) NULL
        ///			,[item_code] [varchar](15) NULL
        ///			,[item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INIT_SCRIPTS {
            get {
                return ResourceManager.GetString("INIT_SCRIPTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from XX_EXTENDED_SETTINGS.
        /// </summary>
        internal static string REMOVE_WARRENTY_SETTINGS {
            get {
                return ResourceManager.GetString("REMOVE_WARRENTY_SETTINGS", resourceCulture);
            }
        }
    }
}
