//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSOne.ViewPlugins.ExtendedWarranty.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSOne.ViewPlugins.ExtendedWarranty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked:.
        /// </summary>
        internal static string Clicked {
            get {
                return ResourceManager.GetString("Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double list view.
        /// </summary>
        internal static string DoubleListView {
            get {
                return ResourceManager.GetString("DoubleListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a double list view.
        /// </summary>
        internal static string DoubleListViewDescription {
            get {
                return ResourceManager.GetString("DoubleListViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello 1.
        /// </summary>
        internal static string Hello1 {
            get {
                return ResourceManager.GetString("Hello1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello 2.
        /// </summary>
        internal static string Hello2 {
            get {
                return ResourceManager.GetString("Hello2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to show the Hello worlds view.
        /// </summary>
        internal static string HelloDescription {
            get {
                return ResourceManager.GetString("HelloDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string HelloWorldCmd {
            get {
                return ResourceManager.GetString("HelloWorldCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        internal static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Profiles16 {
            get {
                object obj = ResourceManager.GetObject("Profiles16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple view.
        /// </summary>
        internal static string SimpleView {
            get {
                return ResourceManager.GetString("SimpleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a simple view.
        /// </summary>
        internal static string SimpleViewDescription {
            get {
                return ResourceManager.GetString("SimpleViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single list view.
        /// </summary>
        internal static string SingleListView {
            get {
                return ResourceManager.GetString("SingleListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows a single list view.
        /// </summary>
        internal static string SingleListViewDescription {
            get {
                return ResourceManager.GetString("SingleListViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store setup.
        /// </summary>
        internal static string StoreSetup {
            get {
                return ResourceManager.GetString("StoreSetup", resourceCulture);
            }
        }
    }
}
